### ISSUE TITLE
removeClippedSubviews not working

### ISSUE THREAD

**Issue by kinhunt** [jaysoo/react-native-parallax-scroll-view#1]
Coll project.

Tried to use it with ListView. removeClippedSubviews={true} has no effect. Important setting for performance improvement.

**Comment by jaysoo** [comment]
@kinhunt Thanks for reporting. I'll have to do some testing.

Which react-native version are you using?

**Comment by kinhunt** [comment]
@jaysoo 0.16

**Comment by jaysoo** [comment]
@kinhunt I can confirm that `removeClippedSubviews` prop gets passed to the inner `ScrollView`, but I'm not sure how to go about testing it is working except memory profiling.

Can you provide some testing details?

I've also updated the example to nest `ListView` under `ParallaxScrollView` instead of the other way around, maybe this will help? https://github.com/jaysoo/react-native-parallax-scroll-view/blob/master/Example/Talks.js#L91-L100

**Comment by kinhunt** [comment]
@jaysoo I followed your example. You can shake and open the RN performance profiler on your device or simulator. It shows the number of views. It is stable if the removeClippedSubviews is ON.

**Comment by jaysoo** [comment]
@kinhunt Sorry for the delayed response. As far as I can tell, the attributes are set on `ScrollView` properly. Perhaps there's something going on in RN 0.16.0 that is causing problems?

I'm going to close this ticket for now, but if you continue to run into this issue feel free to reopen.

**Comment by kinhunt** [comment]
@jaysoo sure. thank you. I will do some tests and give you more details.

**Comment by kinhunt** [comment]
@jaysoo happy new year. Unfortunately, the problem is still there with RN 0.17.0

**Comment by jaysoo** [comment]
@kinhunt I'll take another look at this.

**Comment by jaysoo** [comment]
@kinhunt 

Sorry for the delay, been a busy month so far! I dug into the issue and found that `removeClippedSubviews` is working, but I forgot to add `overflow: hidden` in my [ListView example](https://github.com/jaysoo/react-native-parallax-scroll-view/blob/master/examples/ListView/Talks.js#L205). I've update the example now.

Here's the test I used. The number of views stays constants at around 55 while scrolling down.

![parallax-ssiue-7](https://cloud.githubusercontent.com/assets/53559/12380936/0cc65900-bd4d-11e5-93d9-7552f6e49423.gif)

Going to close this for now, feel free to re-open again if anything else comes up.
