### ISSUE TITLE
'Reveal all' while scrolling before expansion happens

### ISSUE THREAD

**Issue by 9mm** [jaysoo/react-native-parallax-scroll-view#10]
Just an idea I had -- Lets say you had a square image in `renderBackground`, and the phone is `300` wide. Then let's say you  set `parallaxHeaderHeight` to `height * 0.8` (so that it doesnt take up so much room).

It would be cool if, as you scroll down, the parallax would uncover the remaining `0.2` left of the image before 'widening' or becoming elastic. It would allow taller images to be used, so that the user can still see all the content if they want to, but it doesnt take up so much space on the initial page render.

Any idea how I might achieve this? :beers:

**Comment by jaysoo** [comment]
With the 0.17 refactor, this should be possible to do. Will take a look when I get time. :)

**Comment by jaysoo** [comment]
@9mm Closing this one for now because I don't have much time to look at it.
