### ISSUE TITLE
seems method ‘renderFixedHeader’ doesn't work

### ISSUE THREAD

**Issue by coolneka** [jaysoo/react-native-parallax-scroll-view#11]
Views return by method ‘renderFixedHeader’ can't be seen ,I can't find the reason..

**Comment by jaysoo** [comment]
Right now fixed headers only renders if sticky header renders. This can be fixed. 

In the meantime, a workaround is to provide an empty sticky header.

**Comment by jaysoo** [comment]
@coolneka This is now fixed in `0.17.3`.
