### ISSUE TITLE
Feature Request: Option to fadeout background

### ISSUE THREAD

**Issue by generalChaos** [jaysoo/react-native-parallax-scroll-view#12]
Hello and many thanks for the great plugin. The scrollview I have it implemented it for, has a transparent background making it so that when you scroll up the background is still visible behind the list items.  I was wondering if you could add the ability to fadeout the background (same as you have for foreground).
Thanks.

**Comment by jaysoo** [comment]
@generalChaos That should be possible. I'll take a look sometime this week when I get the chance.

**Comment by generalChaos** [comment]
@jaysoo  Thanks.  I actually took a look at the code and you made it really easy to make the change.  I have created a pull request for it, hopefully you'll approve it.  Cheers.  (https://github.com/jaysoo/react-native-parallax-scroll-view/pull/13)

**Comment by jaysoo** [comment]
@generalChaos Thanks for the PR. I have merged an published a new version. :+1:
