### ISSUE TITLE
renderForeground isn't displayed (RN 0.18.1)

### ISSUE THREAD

**Issue by JonathanWi** [jaysoo/react-native-parallax-scroll-view#14]
Hello @jaysoo!

I'm trying to use your component for a RN project. I was going crazy with everything working BUT the renderForeground method, so I simply tried copy/pasting your example with listView, and this is what I've got : 

<img width="375" alt="capture d ecran 2016-02-12 a 09 45 14" src="https://cloud.githubusercontent.com/assets/1074479/13002256/5b61315a-d16d-11e5-8244-b19a0dac2d0f.png">

I haven't changed anything in your code. My best guess is that it's related to `0.18.1`, since the code is unaltered. 

Could you please enlighten me on this issue?
Have a great day

**Comment by jaysoo** [comment]
Thanks for the report, that is rather odd. Will check it out today.

**Comment by JonathanWi** [comment]
Thank you very much @jaysoo, let me know if you have the same result!

**Comment by jaysoo** [comment]
@JonathanWi So I ran the example with RN 0.18.1, and it does render for me. Can you possibly link me to a sample repo where this is not working?

**Comment by JonathanWi** [comment]
Thanks for trying to reproduce this bug. I'm out of office for now, but I'll try to get you this ASAP. You can close this in the meantime, and if something comes up, I'll let you know

**Comment by jaysoo** [comment]
Sounds good. :)
