### ISSUE TITLE
Skicky ToolbarAndroid

### ISSUE THREAD

**Issue by terrysahaidak** [jaysoo/react-native-parallax-scroll-view#15]
Really like your component. I use it with ToolbarAndroid component. I've change animating opacity to transparent of background color to get my toolbar actually visible (title, buttons etc), but still have 3 questions:
1. How can I make elevation of my toolbar? Is it possible? Tried add it when it fully visible, but can't get it work.
2. I wanna it fully visible before I scroll out parallax background view.
3. Sticky but not fixed. How can I get it hide when scroll down, and shows up when I scroll up? But it should not hide when it still in parallax background (like it in the play market does).

**Comment by jaysoo** [comment]
@terrysahaidak If you render the toolbar in the foreground then it might be what you're looking for. I haven't tried it myself, but if you try it first, let me know if anything isn't working. Sample code would help tremendously if you run into any issues.

**Comment by jaysoo** [comment]
@terrysahaidak Closing this for now. Please re-open if you continue to experience the same problem.
