### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by JoeArnone** [jaysoo/react-native-parallax-scroll-view#17]
I have one common case that I would like to do.  When the the header is invisible I would still like to show just the left arrow (back button) similar to the twitter client.  The common case is if you arrived at this view and you can still go back to the previous view on the nav stack.

**Comment by jaysoo** [comment]
@JoeArnone Can you do this within the `renderFixedHeader`?

See the ListView example here: https://github.com/jaysoo/react-native-parallax-scroll-view/blob/master/examples/ListView/Talks.js#L86-L93

Of course, replace "Scroll to top" with a back button, fixed to the left. :)

**Comment by JoeArnone** [comment]
Will try that out.  Thanks and great work on the parallax.

**Comment by jaysoo** [comment]
@JoeArnone Let me know how it goes.

If you run into any issues, let me know about the RN version, and the sample code. :smile:

**Comment by jaysoo** [comment]
@JoeArnone Closing this issue. Please re-open if you experience the same problem. :)
