### ISSUE TITLE
renderBackground Image does not fill height of parallaxHeaderHeight before scrolling

### ISSUE THREAD

**Issue by ruudkalis** [jaysoo/react-native-parallax-scroll-view#19]
Hey! 

Thanks for this great react native component! 

I have tested it on a simple news reader app that shows an article heading, title and HTML body. The parallax effect works fine but upon loading the background image does not fill the complete height of the header. I did not find this in the issues yet. And I wonder if there is a workaround for it. I have tried with different heights of the image and header.. no luck.

This also happens with the nested example. 
 
Here is a GIF of my test, where you see it happen two times.

http://gfycat.com/FirstMeatyBunny

And the code for the render function (contains the [HTMLView component](https://github.com/jsdf/react-native-htmlview))
```

    render () {
        return (
            <ParallaxScrollView
                parallaxHeaderHeight={300}
                renderBackground={() => <Image source={{ uri: this.props.post.thumbnail_images.medium_large.url, width: window.width, height: 300 }}/>}                
                >
                <View style={styles.header}>
                <Text style={styles.headerText}>
                    {this.props.post.title}
                </Text>
                </View>
              <View style={styles.loremBody}>
                <HTMLView
                    value={this.props.post.content}
                    onLinkPress={(url) => console.log('navigating to: ', url)}
                    stylesheet={styles}/>                
                <TouchableOpacity onPress={ () => {this._scrollView.scrollTo(0, 0);}}>
                  <Text style={{color: '#00A7FF'}}>
                    Scroll to top
                  </Text>
                </TouchableOpacity>
              </View>            
            </ParallaxScrollView>
        );
    }
```

**Comment by jaysoo** [comment]
@ruudkalis Hey, thanks for reporting this issue! I'll have a look within the next 2-3 days. It's been pretty busy for me lately.

**Comment by jaysoo** [comment]
@ruudkalis I think the problem is that your image's ratio is not the same as `window.width x 300`. You can try using [`Image#resizeMode`](https://facebook.github.io/react-native/docs/image.html).

e.g.

```js

      <ParallaxScrollView
        parallaxHeaderHeight={300}
        renderBackground={() =>
        <Image
          resizeMode="contain" 
          source={{ uri: `https://placekitten.com/${window.width}/400`, width: window.width, height: 300 }}/>}>
        <Text>Meow!</Text>
      </ParallaxScrollView>
```

**Comment by ruudkalis** [comment]
Thanks for the advice!
