### ISSUE TITLE
Getting tween warning during install

### ISSUE THREAD

**Issue by wootwoot1234** [jaysoo/react-native-parallax-scroll-view#2]
I'm getting the following warning with I run:

    npm install react-native-parallax-scroll-view --save

Warning:

    npm WARN EPEERINVALID react-tween-state@0.1.4 requires a peer of react-dom@^0.14.2 but none was installed.
    npm WARN EPEERINVALID react-tween-state@0.1.4 requires a peer of react@>=0.14 but none was installed.

**Comment by jaysoo** [comment]
@wootwoot1234 I haven't listed any dependencies in `package.json`, it might be another package you have installed previously?

**Comment by wootwoot1234** [comment]
My mistake then, sorry about that. I'll take a look at my other modules.  Cheers.
