### ISSUE TITLE
OnScroll, RefreshControl and onEndReached of nested ListView not working

### ISSUE THREAD

**Issue by avishayil** [jaysoo/react-native-parallax-scroll-view#20]
Hi,
I'm trying to nest the following component inside the ParallaxScrollView:
````
                <ListView
                ref="listview"
                key={"postList"}
                dataSource={this.state.dataSource}
                renderSectionHeader={this.renderSectionHeader}
                renderRow={this.renderArticle}
                renderFooter={(this.state.connError === false) ? this.renderFooter : this.renderErrorView}
                scrollEnabled={this.state.scrollEnabled}
                onScroll={this.onScroll}
                onEndReached={this.onEndReached}
                refreshControl={
                    <RefreshControl
                    refreshing={this.state.isRefreshing}
                    onRefresh={this.onRefresh}
                    colors={['#f7913d', '#f7913d', '#f7913d']}
                    progressBackgroundColor={'#fff'}
                    />}
                    />
````
OnScroll, onEndReached and RefreshControl are not working.
I Also noticed that scroll properties are not changing by setting the OnScroll function on the ParallaxScrollView:

````
    onScroll = () => {
        console.log(this.refs.listview.scrollProperties);
        if (this.refs.listview.scrollProperties.offset + this.refs.listview.scrollProperties.visibleLength >= this.refs.listview.scrollProperties.contentLength){
            // this.onEndReached();
        }
    };
````
I also noticed the this.refs.ParallaxView.state is not updated at the OnScroll event, so I have no idea what is the new offset and what is the new scrollY values of the state.
Any ideas?

**Comment by jaysoo** [comment]
Hi @avishayil, I found it was better to use `ListView#renderScrollComponent` rather than mounting `ParallaxScrollView` as the parent of `ListView`:

```js
<ListView
  renderScrollComponent={props => (
    <ParallaxScrollView
      {...props}
      .../>
  }}
  .../>
                  
```

This gives the ListView a chance to pass its own `onScroll` handlers down to `ParallaxScrollView`, and I think this is how you can get `refreshControl` to work.

I haven't tested this exact approach myself, but I have something similar to this working in an app.

**Comment by avishayil** [comment]
Awesome, thanks!

**Comment by waleedarshad-vf** [comment]
@avishayil onEndReached was working? when you test?
