### ISSUE TITLE
Events are not passed through to the background view

### ISSUE THREAD

**Issue by PublicParadise** [jaysoo/react-native-parallax-scroll-view#24]
#### Steps

In ListView `Talk.js` wrap background's `Image` in a  `TouchableOpacity` like this:

```javascript
          renderBackground={() => (
            <View key="background">
              <TouchableOpacity onPress={() => { AlertIOS.alert('Clicked!') }}>
                <Image source={{uri: 'https://i.ytimg.com/vi/P-NZei5ANaQ/maxresdefault.jpg',
                              width: window.width,
                              height: PARALLAX_HEADER_HEIGHT}}/>
              </TouchableOpacity>  
...
```

Build and run the modified code, then click on the background image.

#### EXPECTED
Alert popping up saying "Clicked!"

#### ACTUAL
No alert.

**Comment by jaysoo** [comment]
@PublicParadise The background cannot be interacted with unfortunately since it is behind the foreground. I would suggest wrapping the foreground with `<TouchableOpacity>` instead.

Closing for now, but please feel free to open again with suggestions, etc.
