### ISSUE TITLE
ListView doesn't take full available height per default

### ISSUE THREAD

**Issue by JonathanWi** [jaysoo/react-native-parallax-scroll-view#3]
Hey, first of all, thanks for an awesome component!

I have a problem regarding using it with a ListView: even when I specify a flex:1 on my ListView, the height doesn't stretch to the bottom of the page : 

![slack for ios upload png](https://cloud.githubusercontent.com/assets/1074479/11956832/63ecbb06-a8bd-11e5-8e96-1a80e1c9efa1.jpeg)

In red here: my ListView, that I wish would take the full available height below.

Is there a way to do so?

Cheers!

**Comment by jaysoo** [comment]
@JonathanWi That's the way `ScrollView` works. The child view of `ScrollView` only take up the height needed to contain its content. I'm not sure if there's much you can do about it other than setting height manually on `ListView`.

What kind of problems are you running into?

If you are trying to set the background color, the current API is to provide `contentBackgroundColor`. I'm looking maybe removing this so the content will take on the styles set on `ListView`.

Another way to use `ListView`, which is by providing a custom `renderScrollComponent`. Like so:

```js
<ListView
  ...
  renderScrollComponent={(props) => (
    <ParallaxScrollView
      {...props}
      renderParallaxHeader={...}
      parallaxHeaderHeight={...}
      ...
    />
  )}
/>
```

Depending on your situation, this may fix your issues.

**Comment by JonathanWi** [comment]
Thank you for your detailed and quick answer!

It's a bit hard to explain the behavior I'm trying to achieve, basically on a lot of screen I have this `<FriendList />` component that displays a ListView *and* a Call to Action, which is absolute positioned to always be displayed at the bottom of the ListView (and over it). This works everywhere because ListView takes up all available space (see screen below). 

![slack for ios upload-1 png](https://cloud.githubusercontent.com/assets/1074479/11957909/dde342ac-a8c4-11e5-9276-be225fb45b7f.jpeg)


I assume `ParallaxScrollView` is giving me this different behavior (i.e the ListView not taking the full height, thus my CTA not appearing at the bottom of the page, but at the bottom of the ListView) because everything is wrapped around a ScrollView, which in turns makes my `flex:1` irrelevant.

I'm aware of how specific my use-case is, so I'd understand if you don't feel like exploring how to fix this.(Also, I have another question incoming so be prepared to be harassed haha)

**Comment by jaysoo** [comment]
@JonathanWi If there's a use case for it, I'd definitely want to support it (if possible). I need to dig in to understand how scrolling works underneath the hood a bit better.

As a workaround, can you wrap the CTA and `ParallaxScrollView` in another component that has `flex: 1`? 

e.g.

```js
<View style={{ flex: 1}}>
  <ListView
    style={styles.container}
    dataSource={ this.state.dataSource }
    renderRow={(rowData) => (
        <View key={rowData} style={ styles.row }>
          <Text style={ styles.rowText }> { rowData } </Text>
        </View>
       )}
    renderScrollComponent={props => (
      <ParallaxScrollView
          {...props}
          ref="ParallaxView"
          parallaxHeaderHeight={ PARALLAX_HEADER_HEIGHT }

          renderBackground={() => (
            <View key="background">
              <Image source={{uri: 'https://i.ytimg.com/vi/P-NZei5ANaQ/maxresdefault.jpg',
                              width: window.width,
                              height: PARALLAX_HEADER_HEIGHT}}/>
            </View>
          )}

          renderParallaxHeader={() => (
            <View key="parallax-header" style={ styles.parallaxHeader }>
              <Image style={ styles.avatar } source={{
                uri: 'https://pbs.twimg.com/profile_images/2694242404/5b0619220a92d391534b0cd89bf5adc1_400x400.jpeg',
                width: AVATAR_SIZE,
                height: AVATAR_SIZE
              }}/>
              <Text style={ styles.sectionSpeakerText }>
                Talks by Rich Hickey
              </Text>
              <Text style={ styles.sectionTitleText }>
                CTO of Cognitec, Creator of Clojure
              </Text>
            </View>
          )}/>
      )}/>
  <View style={{ height: 60, backgroundColor: 'red', alignItems: 'center', justifyContent: 'center' }}>
    <Text style={{ fontSize: 20, color: 'white '}}>Call to Action</Text>
  </View>
</View>
```

**Comment by JonathanWi** [comment]
Thanks again for taking the time!

I could try, and it might work, but all in all that would mean re-writing my "container-agnostic" component. Let me have a look and get back to you about this, as I think it will work. After some tries, I think the behavior I have is to be expected so I will have a hard time keeping my component "as is".

I haven't looked at how your component works under the hood, and that might be the last thing I'll do before going with your solution :)

I'll report back!

**Comment by jaysoo** [comment]
@JonathanWi Let me know. I also welcome any PRs if you find improvements. :smiley:

**Comment by jaysoo** [comment]
@JonathanWi Closing this issue for now. I suggest the workaround I posted above for your particular use case.

Feel free this re-open this issue if you new information/requirements come up.

**Comment by nabilfreeman** [comment]
Hi guys, I encountered a similar issue (not with this component), and I got here from Google. The solution of wrapping the ListView in a `flex: 1` View worked for me 😁
