### ISSUE TITLE
Warning : Failed propType: Invalid prop `colors[0]`

### ISSUE THREAD

**Issue by bozzmob** [jaysoo/react-native-parallax-scroll-view#5]
Hi,

I tried the list view example listed in the examples folder. Here is the [code](https://github.com/bozzmob/react-native-parallax-scroll-view) I have tried.

I am getting the following warning. Please help resolve this.

![screenshot_2015-12-24-22-48-27](https://cloud.githubusercontent.com/assets/1252941/11996835/cacdf6fc-aa91-11e5-9c53-cdece8bca9e6.png)

What am I doing wrong? It's the exact same code I am using in my project.

**Comment by jaysoo** [comment]
This is a bug in the `PullToRefreshView` component of react-native.

https://github.com/facebook/react-native/issues/4663

You can safely ignore it for now until it is patched in RN.

**Comment by bozzmob** [comment]
Sure, thanks @jaysoo  for the reference.
