### ISSUE TITLE
[FATAL]: inputRange must be monotonically increasing 0,NaN

### ISSUE THREAD

**Issue by ChristianTucker** [jaysoo/react-native-parallax-scroll-view#53]
I'm using the example code available on the `README.md` file and obtaining the error provided above, here's the stack-trace. 

![image](https://cloud.githubusercontent.com/assets/21312394/18173456/41f36920-702f-11e6-911e-d003b3ae7fc9.png)

This points to the block of code in index.js

```
translateY: interpolate(scrollY, {
    inputRange: [0, p],
    outputRange: [0, -(p / backgroundScrollSpeed)],
    extrapolateRight: 'extend',
    extrapolateLeft: 'clamp'
})
```

I'm running the latest version of react and react-native and running iOS 9.3 on a simulator.

Just in the event I may have made a mistake and missed it, here's the render code I'm using

```
render() {
        return <ParallaxScrollView>
                    backgroundColor="blue"
                    contentBackgroundColor="pink"
                    parallaxHeaderHeight={410}
                    renderForeground={()=>(<View style={{ height: 300, flex: 1, alignItems: 'center', justifyContent: 'center' }}>
                        <Text>Hello World!</Text>
                    </View>)}>
            <View style={{ height: 500 }}>
                <Text>Scroll me</Text>
            </View>
        </ParallaxScrollView>
    }
```

**Comment by ChristianTucker** [comment]
Issue seemed to fix itself after a few minutes. I got up to go get a drink and came back and the error screen was gone and everything is working fine. I guess the bundle didn't get updated during the reload process.

**Comment by pcooney10** [comment]
Happened to me as well, the cause for anyone who may come across this was a `null` value for the  `parallaxHeaderHeight` prop. (resulting in `NaN` above)
