### ISSUE TITLE
List view and other components flickers when scrolled up

### ISSUE THREAD

**Issue by bozzmob** [jaysoo/react-native-parallax-scroll-view#6]
This is an observation that I came across while testing on the phone.

When I scroll up till the end(when I reach the bottom of list view), all components of the app flicker or drag.

Recorded a [video](https://www.youtube.com/watch?v=_GI5v1HAmko) for more clarity.

**Comment by jaysoo** [comment]
Hi @bozzmob, thanks for reporting this issue. I won't have much time the next few days due to the holidays, but will take a look when I get the chance.

**Comment by bozzmob** [comment]
Sure @jaysoo I will also have a look at it. This is great work! Amazing repo. :+1:  Happy holidays!

**Comment by jaysoo** [comment]
@bozzmob Thanks! Hope you enjoyed your holidays. I'll take a look soon, just getting back into things now.

**Comment by bozzmob** [comment]
@jaysoo Thanks :)

**Comment by jaysoo** [comment]
@bozzmob The flickering should not happen anymore.

There was some problem when updating the dimensions of each subview even though they should not be changing. I fixed this by preventing state updates unless they will cause dimensions to change.

**Comment by bozzmob** [comment]
Thanks for the quick fix. Will check it soon :)
