### ISSUE TITLE
Fade out image

### ISSUE THREAD

**Issue by Ehesp** [jaysoo/react-native-parallax-scroll-view#7]
On the example:

![gif](https://github.com/jaysoo/react-native-parallax-scroll-view/raw/master/demo.android.gif)

To make it more "Android" like, is there any way to make this fade out into the colour of the header rather than instantly change to the base color?

**Comment by jaysoo** [comment]
Hi @Ehesp, this is possible. I need to take a look at the animation opacity animation.

**Comment by Ehesp** [comment]
If it's any help, we do it here:

https://github.com/react-native-material-design/react-native-material-design/blob/master/lib/IconToggle.js

So could update the "opacityValue" on scroll percentage, and just ensure the background colour behind the image is the same as the toolbar?

**Comment by jaysoo** [comment]
Sorry for the delay, been a busy month so far! I dug into the issue and found that `removeClippedSubviews` is working, but I forgot to add `overflow: hidden` in my [ListView example](https://github.com/jaysoo/react-native-parallax-scroll-view/blob/master/examples/ListView/Talks.js#L205). I've update the example now.

Here's the test I used. The number of views stays constants at around 55 while scrolling down.

![parallax-ssiue-7](https://cloud.githubusercontent.com/assets/53559/12380936/0cc65900-bd4d-11e5-93d9-7552f6e49423.gif)

Going to close this for now, feel free to re-open again if anything else comes up.

**Comment by jaysoo** [comment]
Oops, closed the wrong issue. Reopening.

**Comment by jaysoo** [comment]
@Ehesp I just realized the the demo is probably out of date. Here's the current version:

https://github.com/jaysoo/react-native-parallax-scroll-view/blob/master/demo.android.20160117.gif

The opacity is interpolated based on the scroll position.

Let me know if you think the values need to be tweaked, or requires customizable.

https://github.com/jaysoo/react-native-parallax-scroll-view/blob/master/src/index.js#L251-L254

**Comment by jaysoo** [comment]
Closing this issue. Feel free to reopen if anything else comes up.
