### ISSUE TITLE
Foreground is not clickable for size of sticky header.

### ISSUE THREAD

**Issue by hyochan35** [jaysoo/react-native-parallax-scroll-view#80]
Hi. I've used your library today and found strange behavior so I post the issue.

Firstly, my app ui looks like the following.
Image 1:
<img width="318" alt="2017-08-18 5 32 38" src="https://user-images.githubusercontent.com/20625109/29450954-b9339ff2-843b-11e7-9cb0-74876a71bdf1.png">
Image 2:
<img width="318" alt="2017-08-18 5 32 33" src="https://user-images.githubusercontent.com/20625109/29450967-c5bc684e-843b-11e7-8829-c8ac1dddaa13.png">

I have clickable button at the left and right of the header. My buttons are clickable when my navbar has changed to sticky header which is image2. However, foreground navbar buttons won't be clickable which is image 1. I just figured out why this is happening and it was the issue for z-index. In your code, when I change like below, then image1 buttons are clickable again and image2 buttons won't be clicked.

![image](https://user-images.githubusercontent.com/20625109/29451045-27567b9e-843c-11e7-9d3d-5c530d43ced9.png)

I think you need to fix your library so that it will be clickable on both side. You may put some variable to check which one is visible and change their z-index when state has changed.

I'll fix it on my side but wish you to fix this problem also so I can work fine with my other labtop.

Thank you.

**Comment by hyochan35** [comment]
Never mind it was same issue on the below post.

**Comment by kaytee319** [comment]
> Hi. I've used your library today and found strange behavior so I post the issue.
> 
> Firstly, my app ui looks like the following.
> Image 1:
> <img alt="2017-08-18 5 32 38" width="318" src="https://user-images.githubusercontent.com/20625109/29450954-b9339ff2-843b-11e7-9cb0-74876a71bdf1.png">
> Image 2:
> <img alt="2017-08-18 5 32 33" width="318" src="https://user-images.githubusercontent.com/20625109/29450967-c5bc684e-843b-11e7-8829-c8ac1dddaa13.png">
> 
> I have clickable button at the left and right of the header. My buttons are clickable when my navbar has changed to sticky header which is image2. However, foreground navbar buttons won't be clickable which is image 1. I just figured out why this is happening and it was the issue for z-index. In your code, when I change like below, then image1 buttons are clickable again and image2 buttons won't be clicked.
> 
> ![image](https://user-images.githubusercontent.com/20625109/29451045-27567b9e-843c-11e7-9d3d-5c530d43ced9.png)
> 
> I think you need to fix your library so that it will be clickable on both side. You may put some variable to check which one is visible and change their z-index when state has changed.
> 
> I'll fix it on my side but wish you to fix this problem also so I can work fine with my other labtop.
> 
> Thank you.

how did you fix it with zindex? changing zindex didn't help me! Stuck on it for so long..pleasee help
