### ISSUE TITLE
Option to disable scroll acceleration?

### ISSUE THREAD

**Issue by 9mm** [jaysoo/react-native-parallax-scroll-view#9]
Are you guys open to adding this. I love this parallax so much but I don't like how it upsets the expected tactile feedback of dragging.

I could attempt to add it, if you guys are open to it.

**Comment by 9mm** [comment]
After looking at this, I'm not even sure how to disable the scroll acceleration without messing up the rest of the parallax (the image no longer grows or slides when I remove the parts where I think it would be). Any ideas? :|

**Comment by jaysoo** [comment]
@9mm Can you provide a small example to show the problem at hand? I can try to find a solution once I know the full detail of the problem.

**Comment by jaysoo** [comment]
Also, any description, screenshots, GIFs, etc. to help illustrate the problem might help too.

**Comment by 9mm** [comment]
Sure!

Essentially the 'problem' looks more like a design decision rather than a bug. This is such a fantastic library, however and definitely want to use it.

I believe the expected behavior when one drags their finger is that the content drags at the same speed as their thumb moves.

This library however, in order to achieve the parallax effect, moves the header image at `1x` dragging speed while the content travels at `~2x` drag speed.

I believe the expected behavior should be that the content travels at `1x` speed, and the image moves at `~0.5x` speed.

This manifests itself I think as a confusion because you might be using 50 other pages of the app which involve long lists, and they get a tactile feedback response they're used to, and then suddenly they land on a page which zooms at 2x the speed it's a little jarring.

I looked at it to try to fix it myself, however and I am just unsure. I think I am too dumb to figure that out in a reasonable amout of time :laughing:

**Comment by jaysoo** [comment]
@9mm I see. So basically, the top of the content scrolls up faster due to the parallax view then it would using a normal list view.

For example, if a user drags their finger up 10 dp on a ListView, they would drag the content up by 10 dp. However, with the ParallaxScrollView, when the user drags their finger up 10 dp, the content goes up more than 10 dp.

Is that correct?

**Comment by 9mm** [comment]
Yep, exactly - that's correct.

I think a lot of other parallax solutions solve this dilemma by having the image go slower than drag speed, rather than the same speed (basically that becomes the variable which changes rather than the content which would remain constant).

And yes you're right about the scrolling is faster only at the start, and then it slows down to `1x` speed. I just think it would be great if it were `1x` 100% of the time, and then the image becomes the variable which changes (probably slower, I think having that go faster wouldn't work)

**Comment by jaysoo** [comment]
I can take a look tonight. The main work would be to come up with the formula for header height, background image offset, etc based on the scroll position of the scroll view.

**Comment by 9mm** [comment]
You are so immensely awesome, **thank you so much**.

**Comment by 9mm** [comment]
I think FWIW it might be cool to have both options, like `acceleratedMode` or something

**Comment by jaysoo** [comment]
@9mm I don't think we need a different behaviour for it. I didn't really realize it before, but I think what you described should be the only correct behaviour.

Scrolling speed can be changed by providing a different ScrollView via `renderScrollComponent` prop.

Thanks for bringing this to my attention. :)

**Comment by 9mm** [comment]
I have a cool idea, if you haven't already started yet. It's not a big deal, just something I am experiencing, and if you have to do some of this over anyway, it might be worth pointing out.

Lets say you had a square image in `renderBackground`, and the phone is `300` wide. Then let's say you  set `parallaxHeaderHeight` to `height * 0.8` (so that it doesnt take up so much room).

It would be cool if, as you scroll down, the parallax would uncover the remaining `0.2` left of the image before 'widening' or becoming elastic. It would allow taller images to be used, so that the user can still see all the content if they want to, but it doesnt take up so much space on the initial page render.

**Comment by jaysoo** [comment]
@9mm I have some changes locally that fixes the speed issue. I'm thinking about adding two optional props for controlling the scrolling speed of the background and header, relative to the scroll content.

The thing I'm trying to figure out is how I can persist press events to the header, since I have it behind the scroll content at the moment (for performance and simplicity reasons).

Can you open your last suggestion as a separate issue? I've that behaviour in other components before, and can probably address it at a later date.

**Comment by 9mm** [comment]
Sure! And I liked your idea about the props controlling the speed.

**Comment by jaysoo** [comment]
Out of curiosity, do you use any press handlers on the header? Because you could try the `9-scroll-speed` branch if you don't need it.

Not sure if I can get this working tonight. Need to look into the gesture system or an alternative way to set this up.

**Comment by 9mm** [comment]
Yep, I use an `onPress` inside `renderParallaxHeader`

**Comment by jaysoo** [comment]
Gonna take another shot tonight by redoing the scrolling behaviour a bit. THe problem with layering the header behind scroll component is that there is no way to interact with i.

**Comment by jaysoo** [comment]
@9mm Can you try `npm install react-native-parallax-scroll-view@0.17.0-rc`?

The updated README is [here](https://github.com/jaysoo/react-native-parallax-scroll-view/tree/0.17-stable).

The new version will get rid of parallax effect on the foreground header (unfortunately). But I think it's more important to keep the scroll speed in sync with user scroll speed.

I am coming up with some ideas on having parallax effect on layer elements above background, but they most likely won't respond to touch events.

Can you give it a shot and let me know?

**Comment by 9mm** [comment]
It works great so far. Is it possible not to have the foreground fade out to 0 opacity?

**Comment by 9mm** [comment]
As far as the foreground, thats something I won't ever use parallax on, so that part doesn't bother me.

It works with touch events perfectly as well.

Great work!

The last thing I will do is check the performance on old iPhone, because thats one thing your library did 100x better than the other parallax library.

**Comment by jaysoo** [comment]
Yeah, there is a fade, but it is scaled to be non-linear with a bias towards the end. I can tweak it so it's more linear (maybe with an option later to take in user-specified value).

Let me know re: performance. That's something I definitely care about. :)

Thanks!

**Comment by 9mm** [comment]
Yeah I'd definitely say have an option to be constant the whole way without fade. That was another thing I also really liked about your lib.

Will check perf tonight

**Comment by 9mm** [comment]
Tested on an older iphone and performance is :100: top notch. Awesome work!

**Comment by 9mm** [comment]
Let me know what your thoughts are on the opacity thing. Thanks again, you are so awesome :D

**Comment by jaysoo** [comment]
I'm going to be adding a `fadeOutForeground` boolean prop tonight (default to `true`). Potentially I could provide further customizations by allowing an animation factory function or something. Will need to think about it more. :)

**Comment by jaysoo** [comment]
@9mm Just pushed version `0.17.2` with a more prominent fade out of the foreground. Let me know how it's working out and we can close this issue.

**Comment by 9mm** [comment]
It's absolutely awesome!

![](https://media.giphy.com/media/Cj3Ce7e8h2EKY/giphy.gif)
